### ISSUE TITLE
컬럼명 문의드립니다

### ISSUE THREAD

**Issue by ted9219** [slajou/DS511_data#1]
안녕하세요 이슬 교수님, 
Data statistics 수강중인 의료정보학과 김청수입니다.

기말 과제 관련하여 데이터 분석 중에 있는데,
메일로 송부해주신 description 파일 및 readme file 내의 컬럼 설명과 
데이터 내 컬럼명에 혼동이 있어 문의드립니다.

description 의 변수는 T, AP, RH, V, EP 이고 
배포해주신 데이터 내의 변수는 AT, V, AP,RH, PE 인데

컬럼의 T = AT 이고, EP  = PE로 생각되는데,
혹시 맞는 부분인지 문의드립니다. 

감사합니다.

아주대학교 의료정보학과
김청수 드림

**Comment by slajou** [comment]
네 그렇게 mapping하면 됩니다.

**Comment by ted9219** [comment]
감사합니다 ^^
